select 	user_name(a.uid) as [RolName],
	(CASE [action]
	WHEN 26 THEN 'REFERENCES'
	WHEN 178 THEN 'CREATE FUNCTION'
	WHEN 193 THEN 'SELECT'
	WHEN 195 THEN 'INSERT'
	WHEN 196 THEN 'DELETE'
	WHEN 197 THEN 'UPDATE'
	WHEN 198 THEN 'CREATE TABLE'
	WHEN 203 THEN 'CREATE DATABASE'
	WHEN 207 THEN 'CREATE VIEW'
	WHEN 222 THEN 'CREATE PROCEDURE'
	WHEN 224 THEN 'EXECUTE'
	WHEN 228 THEN 'BACKUP DATABASE'
	WHEN 233 THEN 'CREATE DEFAULT'
	WHEN 235 THEN 'BACKUP LOG'
	WHEN 236 THEN 'CREATE RULE'
	END) as [Action],
	(CASE protecttype
	WHEN 204 THEN 'GRANT_W_GRANT'
	WHEN 205 THEN 'GRANT'
	WHEN 206 THEN 'DENY'
	END) as [ProtectType],
	object_name(id) 'ObjectName'
from sysprotects a inner join sysusers b
		on a.uid = b.uid
where a.uid <> 0 and issqlrole = 1
